//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpopZtation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int customerId { get; set; }
        public int albumId { get; set; }
        public int qty { get; set; }
    
        public virtual album album { get; set; }
        public virtual customer customer { get; set; }
    }
}
